import {TypeOfError, TypeOfPrinter} from 'utils/enums';

export interface AppStateI {
  ticketStatus: 'checking' | 'acepted' | 'canceled' | 'init';
  products: Product[];
  ticketInfo: Ticket | null;
  totalPorducts: number;
  isLoading: boolean;
  messageLoading: string;
  error: boolean;
  typeOfError: TypeOfError | null;
  printer: boolean;
  typeOfPrinter: TypeOfPrinter;
}

// Generated by https://quicktype.io

export interface ITicketResponse {
  ticket: Ticket;
  products: Product[];
}

export interface Product {
  productName: string;
  reasonName: string;
  quantityProductsReturn: number;
  priceByUnit: string;
  productColor: string;
  productSize: string;
}

export interface Ticket {
  id: string;
  ticketId: string;
  identityDocument: string;
  email: string;
  ticketStatus: number;
  ticketStatusName: string;
  categoryId?: number;
  categoryName?: string;
}
