import {TypeOfError, TypeOfPrinter} from 'utils/enums';

export interface AppStateI {
  ticketStatus: 'checking' | 'acepted' | 'canceled' | 'init';
  token: string;
  products: Product[];
  ticketInfo: Ticket | null;
  totalPorducts: number;
  isLoading: boolean;
  messageLoading: string;
  error: boolean;
  typeOfError: TypeOfError | null;
  printer: boolean;
  typeOfPrinter: TypeOfPrinter;
  resetAnimation: boolean;
}

// Generated by https://quicktype.io

export interface ITicketResponse {
  ticket: Ticket;
  products: Product[];
}

export interface Product {
  order_detail_id: string;
  order_id: string;
  ticket_id: string;
  product_name: string;
  reason_name: string;
  quantity_products_return: number;
  price_by_unit: string;
  product_color: string;
  product_size: string;
}

export interface Ticket {
  order_id: string;
  ticket_id: string;
  identity_document: string;
  email: string;
  status_request: number;
  status_request_name: string;
  category_id: number;
  category_name: string;
}
