import {SvgProps} from 'react-native-svg';

export type TicketStatus =
  | 'ticket_used'
  | 'ticket_security'
  | 'ticket_electro'
  | 'ticket_canceled_client'
  | 'ticket_canceled_personal'
  | 'ticket_canceled'
  | 'ticket_canceled_wifi';

export interface TicketContent {
  IconSvg: React.FC<SvgProps>;
  title: string;
  message: string;
}

// Generated by https://quicktype.io

export interface ClientResponse {
  success: boolean;
  clients: Client[];
}

export interface Client {
  id: number;
  name: string;
  lastName: string;
  dateOfBirth: string;
  createdAt: string;
  updatedAt: string;
}

// Generated by https://quicktype.io

export interface ITicketResponse {
  ticket: Ticket;
  products: Product[];
}

export interface Product {
  productName: string;
  reasonName: string;
  quantityProductsReturn: number;
  priceByUnit: string;
  productColor: string;
  productSize: string;
}

export interface Ticket {
  id: string;
  ticketId: string;
  identityDocument: string;
  email: string;
  ticketStatus: number;
  ticketStatusName: string;
}
